jobs:
- job: Windows_MSVC_x86
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: project/azure-pipelines/msvc_x86.yml

- job: Windows_MSVC_x64
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: project/azure-pipelines/msvc_x64.yml
  
- job: Windows_MinGW
  pool:
    vmImage: VS2017-Win2016
  steps:
  - template: project/azure-pipelines/mingw.yml

#- job: Linux_Clang
#  pool:
#    vmImage: Ubuntu-16.04
#  steps:
#  - template: project/azure-pipelines/linux.yml
