jobs:
- job: windows_msvc
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: project/azure-pipelines/msvc.yml

- job: windows_mingw
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: project/azure-pipelines/mingw.yml

- job: macos
  pool:
    vmImage: 'macos-latest'
  steps:
  - template: project/azure-pipelines/macos.yml

- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: project/azure-pipelines/linux.yml

- job: publish
  dependsOn:
    - windows_msvc
    - linux
    - macos
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: $(Build.ArtifactStagingDirectory)
        artifactName: bee
