jobs:
- job: msvc
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: project/azure-pipelines/msvc.yml

- job: mingw
  pool:
    vmImage: 'windows-latest'
  steps:
  - template: project/azure-pipelines/mingw.yml

- job: macos
  pool:
    vmImage: 'macos-latest'
  steps:
  - template: project/azure-pipelines/macos.yml

- job: linux
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - template: project/azure-pipelines/linux.yml
