steps:
- bash: |
   sudo apt-get update
   sudo apt-get install -y libreadline-dev ninja-build
  displayName: Init

- bash: |
   ninja -f ninja/linux.ninja
  displayName: Compile

- bash: |
   build/linux/bin/bootstrap test/test.lua
  displayName: Test
