steps:
- bash: |
   sudo xcode-select -s /Applications/Xcode_10.2.app
   brew install ninja
  displayName: Init

- bash: |
   ninja -f ninja/macos.ninja
  displayName: Compile

- bash: |
   build/macos/bin/bootstrap test/test.lua
  displayName: Test

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: build/macos/bin
    artifactName: bee-macos
