steps:
- bash: |
   sudo xcode-select -s /Applications/Xcode_10.1.app
   brew install ninja
  displayName: Init

- bash: |
   ninja -f build/macos/make.ninja
  displayName: Compile

- bash: |
   bin/macos_release/bootstrap test/test.lua
  displayName: Test
