steps:
- script: |
   choco install -y msys2
   refreshenv
   c:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu"
   exit
  displayName: 'Install msys2'

- script: |
   c:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu mingw-w64-x86_64-gcc ninja"
   c:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Su"
   exit
  displayName: 'Update mingw'

- script: |
   cd make
   luamake mingw-init.lua c:\tools\msys64
   luamake mingw.lua gcc --version
   luamake mingw.lua ninja -f build/mingw/make.ninja
  displayName: Compile

- script: |
   cd make
   luamake mingw.lua .\bin\mingw_release\bee.exe .\test\test.lua
  displayName: Test
