steps:
- script: |
   choco install -y msys2
   refreshenv
   c:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu"
   exit
  displayName: 'Install msys2'

- script: |
   c:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Syu mingw-w64-x86_64-gcc ninja"
   c:\tools\msys64\usr\bin\bash.exe -lc "pacman --noconfirm -Su"
   exit
  displayName: 'Update mingw'

- script: |
   cd make
   lua mingw-init.lua c:\tools\msys64
   lua mingw.lua gcc --version
   lua mingw.lua ninja -f ninja/mingw.ninja
  displayName: Compile

- script: |
   cd make
   lua mingw.lua .\build\mingw\bin\bootstrap.exe .\test\test.lua
  displayName: Test
