steps:
- script: |
   choco install -y ninja
   refreshenv
  displayName: Init

- script: |
   make\lua.exe make\msvc.lua ninja -f ninja\msvc.ninja
  displayName: Compile

- script: |
   build\msvc\bin\bootstrap.exe test\test.lua
  displayName: Test

- task: CopyFiles@2
  inputs:
    Contents: |
      *.exe
      *.dll
      *.lua
    SourceFolder: 'build/msvc/bin'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/windows'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: bee
