steps:
- script: |
   choco install -y ninja
   refreshenv
  displayName: Init

- script: |
   make\lua.exe make\msvc.lua ninja -f ninja\msvc.ninja
  displayName: Compile

- script: |
   build\msvc\bin\bootstrap.exe test\test.lua
  displayName: Test

- task: CopyFiles@2
  displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
  inputs:
    Contents: |
     build/msvc/bin/*.exe
     build/msvc/bin/*.dll
    TargetFolder: '$(Build.ArtifactStagingDirectory)/msvc'

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: $(Build.ArtifactStagingDirectory)
    artifactName: bee
