name: build
on: push
jobs:
  compile:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-16.04, ubuntu-18.04, ubuntu-20.04, macos-latest]
        arch: [x86, x64]
        mode: [debug, release]
        exclude:
        - os: ubuntu-16.04
          arch: x86
        - os: ubuntu-18.04
          arch: x86
        - os: ubuntu-20.04
          arch: x86
        - os: macos-latest
          arch: x86
    steps:
    - uses: actions/checkout@v1
      with:
        ref: refs/heads/master
        submodules : recursive
    - uses: actboy168/setup-luamake@master
      with:
        arch: ${{ matrix.arch }}
    - run: luamake -mode ${{ matrix.mode }}
