name: build

on: [push, pull_request]

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        submodules : recursive
    - name: Init
      run: |
        choco install -y ninja
        refreshenv
    - name: Compile
      run: |
        make\lua.exe make\msvc.lua ninja -f ninja\msvc.ninja
    - name: Test
      run: |
        build\msvc\bin\bootstrap.exe test\test.lua

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        submodules : recursive
    - name: Init
      run: |
        sudo apt-get update
        sudo apt-get install -y libreadline-dev ninja-build
    - name: Compile
      run: |
        ninja -f ninja/linux.ninja
    - name: Test
      run: |
        build/linux/bin/bootstrap test/test.lua

  macos:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 1
        submodules : recursive
    - name: Init
      run: |
        brew install ninja
    - name: Compile
      run: |
        ninja -f ninja/macos.ninja
    - name: Test
      run: |
        build/macos/bin/bootstrap test/test.lua
